version: '3'

services:
  sonarqube:
    image: sonarqube:8.0-developer-beta
    container_name: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:15432/sonarqube
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=pass@word1
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "pass@word1"
    ports:
      - "15432:5432"
    volumes:
      - /Users/diovanemendes/postgreSql:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diovane@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass@word1"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge